server:
  port: 8080

spring:
  application:
    name: my-take-out
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${phn.db.host}:${phn.db.port}/my_take_out?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${phn.db.un}
    password: ${phn.db.pw}
logging:
  level:
    com.phn: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: "外卖系统接口文档"
    description: "外卖系统"
    email: 3577405535@qq.com
    concat: 彭皓楠
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.phn.mytakeout.controller
phn:
  jwt:
    secret: phn-takeout
    ttl: 7200000
  auth:
    excludePaths:
      - /admin/employee/login
  db:
    host: 192.168.60.133
    port: 3306
    un: root
    pw: 123